SetupMode: true
Debug: false
Settings:
  LobbyServer: spleefLobby
  SecondsBeforeStart: 30
  SecondsBeforeRestart: 15
  MaxSnowballs: 32
  TitlesEnabled: true
  SoundsEnabled: true
MySQL:
  Host: 127.0.0.1
  Port: 3306
  Username: root
  Password: password
  Database: zspleef
  UseSSL: false
Arena: {}