name: zSpleef
version: '1.0'
main: it.zmario.zspleef.Main
authors: [zMario]
description: A new spleef plugin.
softdepend: [PlaceholderAPI]
commands:
  spleef:
    description: Main command of the plugin.